apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: example-keycloak
  labels:
    app: sso
  namepsace: keycloak-operator
spec:
  instances: 1
  externalAccess:
    enabled: True
  externalDatabase:
    enabled: false

