apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rhbk-operator-ns.yaml
  - postgres-ns.yaml
  - subscription.yaml
  - postgres.yaml
  - postgres-svc.yaml
  - keycloak.yaml
  