apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: postgres-db
  namespace: postgres
spec:
  selector:
    app: postgresql-db
  ports:
  - port: 5432
    targetPort: 5432
