apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: postgresql-db
  namespace: postgres
spec:
  serviceName: postgresql-db
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          image: registry.redhat.io/rhel8/postgresql-12
          volumeMounts:
            - mountPath: /data
              name: cache-volume
          env:
            - name: POSTGRESQL_USER
              value: rhbkuser
            - name: POSTGRESQL_PASSWORD
              value: testpassword
            - name: POSTGRESQL_DATABASE
              value: keycloak
      volumes:
        - name: cache-volume
          emptyDir: {}